stages:
  - build
  - deploy

build:
  stage: build
  image: gitlab-registry.cern.ch/cloud/gitbook-ebook
  before_script:
    - mkdir public
    # Fetching a specific GitBook version due to the bug described at https://github.com/chusiang/gitbook.ansible.role/issues/5
    - gitbook fetch 2.6.7
  script:
    - gitbook install
    - gitbook build $CI_PROJECT_DIR $CI_PROJECT_DIR/_book
    - gitbook pdf $CI_PROJECT_DIR $CI_PROJECT_DIR/book.pdf
    - cp -r $CI_PROJECT_DIR/_book/* public/
    - cp $CI_PROJECT_DIR/book.pdf public/
  artifacts:
    paths:
      # Upload as an artifact the folder where the output has been generated
      # This will attach to the job the output. It can be browsed or downloaded
      - public
    # Make it vanish in 1 hour
    expire_in: 1 hour
  tags:
    - docker

deploy:
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  only:
    - master
  script:
    # Script that performs the deploy to EOS. Makes use of the variables defined in the project
    # It will copy the generated content to the folder in EOS
    - deploy-eos
  # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []
  tags:
    - docker
